name: Deploy

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Deployment environment
        default: development
        type: choice
        options:
          - feature
          - development
          - test
          - acceptance
          - production

env:
  DEFAULT_DEPLOYMENT_ENVIRONMENT: feature
  DOCKER_REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Docker registry
        uses: docker/login-action@v3
        with:
          registry: {% raw %}${{ env.DOCKER_REGISTRY }}{% endraw %}
          username: {% raw %}${{ github.actor }}{% endraw %}
          password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

      - name: Set Docker image tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          {%- if cookiecutter.private_package_repository_name %}
          secrets: |
            "poetry_auth=[http-basic.{{ cookiecutter.private_package_repository_name|slugify }}]
            username = ""{% raw %}${{{% endraw %} secrets.POETRY_HTTP_BASIC_{{ cookiecutter.private_package_repository_name|slugify(separator="_")|upper }}_USERNAME }}""
            password = ""{% raw %}${{{% endraw %} secrets.POETRY_HTTP_BASIC_{{ cookiecutter.private_package_repository_name|slugify(separator="_")|upper }}_PASSWORD }}""
            "
          {%- endif %}
          tags: |
            {% raw %}${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ github.repository }}:${{ github.event.inputs.environment || env.DEFAULT_DEPLOYMENT_ENVIRONMENT }}{% endraw %}
            {% raw %}${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ github.repository }}:${{ env.GIT_TAG }}{% endraw %}
          target: app
