version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: scope
    groups:
      ci-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
      prefix-development: "build"
      include: scope
    allow:
      {%- if cookiecutter.project_type == "app" %}
      - dependency-type: production
      {%- endif %}
      - dependency-type: development
    versioning-strategy: increase
    groups:
      {%- if cookiecutter.project_type == "app" %}
      runtime-dependencies:
        dependency-type: production
      {%- endif %}
      development-dependencies:
        dependency-type: development
