version: "3.9"

services:
  dev:
    build:
      context: .
      target: dev
      {%- if cookiecutter.private_package_repository_name %}
      secrets:
        - poetry_auth
      {%- endif %}
    tty: true
    entrypoint: []
    command:
      [
        "sh",
        "-c",
        {%- if cookiecutter.private_package_repository_name %}
        "cp --update /var/lib/poetry/poetry.lock /app/ && cp --update /var/lib/git/* /app/.git/hooks/ && ln -s /run/secrets/poetry_auth /root/.config/pypoetry/auth.toml && sleep infinity"
        {%- else %}
        "cp --update /var/lib/poetry/poetry.lock /app/ && cp --update /var/lib/git/* /app/.git/hooks/ && sleep infinity"
        {%- endif %}
      ]
    environment:
      {%- if not cookiecutter.private_package_repository_name %}
      - POETRY_PYPI_TOKEN_PYPI
      {%- endif %}
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    hostname: "{{ cookiecutter.package_name|slugify }}-dev.local"
    ports:
      - "8000"
    expose:
      - "8000"
    {%- endif %}
    {%- if cookiecutter.private_package_repository_name %}
    secrets:
      - poetry_auth
    {%- endif %}
    volumes:
      - .:/app/:cached
      - ~/.gitconfig:/etc/gitconfig:cached
      - ${SSH_AGENT_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/run/host-services/ssh-auth.sock:cached
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:cached
  {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int or cookiecutter.with_typer_cli|int %}
  app:
    build:
      context: .
      target: app
      {%- if cookiecutter.private_package_repository_name %}
      secrets:
        - poetry_auth
      {%- endif %}
    tty: true
    {%- if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}
    hostname: "{{ cookiecutter.package_name|slugify }}.local"
    ports:
      - "8000"
    expose:
      - "8000"
    {%- endif %}
    profiles:
      - app
  {%- endif %}
{%- if cookiecutter.private_package_repository_name %}

secrets:
  poetry_auth:
    file: $POETRY_AUTH_TOML_PATH
{%- endif %}
